### ISSUE TITLE
Kill selection

### ISSUE THREAD

**Issue by AutoSponge** [jcsteh/axSHammer#1]
What are your thoughts on a list of capabilities with on/off toggle buttons? Either in a devtools panel or popup panel? Or would 
a help overlay and hot-keys work better?

**Comment by jcsteh** [comment]
There are two dimensions to consider here:

1. These tools don't currently monitor the page for changes and automatically apply the tweak, so they're not "toggleable". That might be possible, but whether that's a good idea is an open question. Given the risk of inaccuracy or unreliability, I think users need to be aware when these tweaks have occurred. If a user runs a tool explicitly and it labels a button, they know there's a risk that label might be inaccurate or incorrect. On the other hand, if the tweak just happens automatically, the user won't know whether that label was provided by the page author (presumably accurate) or AxSHammer (potentially inaccurate).
2. What are you trying to achieve? Why is a panel better than the context menu? For keyboard users, applications key, x, e is very quick and efficient. Having to open a panel is potentially less efficient. You could have a shortcut key for the panel, but if it basically just displays a menu anyway, I'm not convinced it's any better than the context  menu (and certainly slower for screen reader users).

**Comment by AutoSponge** [comment]
1. Good point.
2. I was thinking along the lines of the [Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) extension. It can apply user styles to specific pages or be toggled to run against all pages. I imagined that would need something more robust than the context menu, but maybe not. For instance, knowing that a particular ecommerce site will spam you with aria-live regions, you could set axSHammer to always kill aira-live on their domains. Based on your comments, I imagine a notification would help remind the user that the kill was applied.

Some features, like the font-awesome kill, could be detected with fairly high accuracy. But it may not be worth the effort. Either way, I like the idea and I am willing to help if you change your mind.

**Comment by jcsteh** [comment]
I understand. It's true that we'd probably need a more advanced user interface if we were going to allow for saving settings per domain, etc.

I figured these kinds of hacks were too risky to apply automatically, but you raise a good point that a notification might help mitigate this concern.

The problem with the font-awesome exposure is that some of these icons are deliberately suppressed by authors (on "accessible" sites) because they are effectively decorative. Applying this automatically would make the site less accessible in those cases, rather than more. Still, that does strengthen the argument for considering domain auto-apply.

Thanks for your interest and thoughts.
